(function(){
const sb=window.rgiptSupabase;if(!sb){document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#loginStatus')?.classList.remove('hidden');document.querySelector('#loginStatus').textContent='Supabase is not configured. Edit js/config.js.'});return;}
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const ASSET_BUCKET='site-assets';
const defs={
 notes:{label:'Subject Notes',table:'notes',fields:[['title','Title','text',1],['subject_code','Subject Code','text',0],['semester','Semester','number',0],['description','Description','textarea',0],['file_url','Note PDF / File','file',0],['published','Published','checkbox',0]]},
 syllabus:{label:'Syllabus',table:'syllabus',fields:[['title','Title','text',1],['batch','Batch','text',0],['semester','Semester','number',0],['file_url','Syllabus PDF','file',1],['published','Published','checkbox',0]]},
 galleries:{label:'Department Gallery',table:'galleries',fields:[['title','Gallery Title','text',1],['description','Description','textarea',0],['cover_image','Cover Image','image',0],['published','Published','checkbox',0]]},
 laboratories:{label:'Laboratories',table:'laboratories',fields:[['name','Lab Name','text',1],['description','About','textarea',0],['location','Location','text',0],['image_url','Lab Image','image',0],['map_url','Google Maps / Map URL','url',0],['published','Published','checkbox',0]]},
 equipment:{label:'Lab Equipment',table:'equipment',fields:[['laboratory_id','Laboratory','labselect',1],['name','Equipment Name','text',1],['description','Description','textarea',0],['specifications','About / Specifications','textarea',0],['image_url','Equipment Image','image',0],['manual_url','Equipment Manual (PDF)','file',0],['published','Published','checkbox',0]]},
 alumni:{label:'Alumni',table:'alumni',fields:[['name','Name','text',1],['batch','Batch','text',0],['position','Position','text',0],['company','Company / Organization','text',0],['bio','Bio','textarea',0],['photo_url','Photo','image',0],['linkedin_url','Profile URL','url',0],['featured','Featured on homepage','checkbox',0],['published','Published','checkbox',0]]},
 locations:{label:'Lab & Classroom Locations',table:'locations',fields:[['name','Name','text',1],['type','Type (Lab/Classroom/etc.)','text',1],['building','Building','text',0],['room','Room','text',0],['description','Description','textarea',0],['map_url','Map URL','url',0],['published','Published','checkbox',0]]},
 notices:{label:'Notices',table:'notices',fields:[['title','Title','text',1],['date','Date','date',1],['description','Description','textarea',0],['file_url','Notice PDF / File','file',0],['published','Published','checkbox',0]]}
};
let current='dashboard', editing=null;
function setStatus(msg,type=''){const e=$('#pageStatus');if(e){e.className='status '+type;e.textContent=msg;e.classList.remove('hidden');}}
function inputField([key,label,type,required],obj={}){
 if(type==='checkbox')return `<div class="field"><label class="check"><input id="f_${key}" type="checkbox" ${obj[key]?'checked':''}> ${esc(label)}</label></div>`;
 if(type==='labselect')return `<div class="field"><label>${esc(label)}</label><select id="f_${key}" ${required?'required':''}><option value="">Loading laboratories…</option></select></div>`;
 if(type==='file'||type==='image'){
   const accept=type==='image'?'image/*':'.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,application/pdf';
   const existing=obj[key]?`<div class="current-file">Current: <a href="${esc(obj[key])}" target="_blank" rel="noopener">Open current file</a></div>`:'';
   return `<div class="field ${type==='file'?'':'media-field'}"><label>${esc(label)}</label><input id="f_${key}" type="file" accept="${accept}"><input id="u_${key}" type="hidden" value="${esc(obj[key]||'')}">${existing}<span class="small">Choose a new ${type==='image'?'image':'file'} to upload. It will be stored automatically.</span></div>`;
 }
 return `<div class="field ${type==='textarea'?'full':''}"><label>${esc(label)}</label>${type==='textarea'?`<textarea id="f_${key}" ${required?'required':''}>${esc(obj[key]||'')}</textarea>`:`<input id="f_${key}" type="${type}" value="${esc(obj[key]||'')}" ${required?'required':''}>`}</div>`;
}
function menu(){const items=[['dashboard','Dashboard'],...Object.entries(defs).map(([k,v])=>[k,v.label]),['gallery_photos','Gallery Photos']];$('#menu').innerHTML=items.map(([k,l])=>`<button class="${k===current?'active':''}" data-page="${k}">${esc(l)}</button>`).join('');document.querySelectorAll('#menu button').forEach(b=>b.onclick=()=>{current=b.dataset.page;render()});}
async function count(table){const {count}=await sb.from(table).select('*',{count:'exact',head:true});return count||0}
async function dashboard(){const names=Object.keys(defs);const vals=await Promise.all(names.map(k=>count(defs[k].table)));$('#content').innerHTML=`<div id="pageStatus" class="status hidden"></div><div class="panel"><h2>Welcome</h2><p>Use the sections on the left to add or update website content. Published records appear on the public website automatically.</p><p class="small">Files and images can now be uploaded directly from this dashboard. They are stored in Supabase Storage.</p></div><div class="stats">${names.slice(0,4).map((k,i)=>`<div class="stat"><b>${vals[i]}</b><span>${esc(defs[k].label)}</span></div>`).join('')}</div><div class="panel"><h2>Upload workflow</h2><ol><li>Choose a PDF/image/file in the relevant form.</li><li>Click Save — the file is uploaded automatically.</li><li>Tick Published when you want it visible.</li><li>Open the website and refresh.</li></ol></div>`}
async function records(def){const {data,error}=await sb.from(def.table).select('*').order('created_at',{ascending:false});if(error){setStatus(error.message,'error');return []}return data||[]}
async function laboratories(){const {data,error}=await sb.from('laboratories').select('id,name').order('name');if(error){setStatus(error.message,'error');return []}return data||[]}
async function fillLabSelect(value=''){const sel=$('#f_laboratory_id');if(!sel)return;const labs=await laboratories();sel.innerHTML='<option value="">Select laboratory</option>'+labs.map(x=>`<option value="${esc(x.id)}" ${x.id===value?'selected':''}>${esc(x.name)}</option>`).join('');}
async function page(key){const def=defs[key];editing=null;$('#content').innerHTML=`<div id="pageStatus" class="status hidden"></div><div class="panel"><h2>${esc(def.label)}</h2><p class="small">Create, edit, publish or delete records. Files/images upload directly to Supabase Storage.</p><form id="recordForm"><div class="form-grid">${def.fields.map(f=>inputField(f)).join('')}</div><div class="actions"><button class="btn gold" type="submit" id="saveBtn">Save</button><button class="btn light" type="button" id="clearBtn">Clear</button></div></form></div><div class="panel"><h2>Existing records</h2><div id="records" class="records">Loading…</div></div>`;$('#recordForm').onsubmit=e=>save(e,key,def);$('#clearBtn').onclick=()=>{editing=null;page(key)};if(def.fields.some(f=>f[2]==='labselect'))await fillLabSelect();await refreshRecords(key,def)}
async function refreshRecords(key,def){const rows=await records(def);const box=$('#records');if(!box)return;box.innerHTML=rows.length?rows.map(r=>`<div class="record"><div><h3>${esc(r.title||r.name||'Untitled')}</h3><p>${esc(r.description||r.company||r.location||'')}</p><p>ID: ${esc(r.id)}</p><p>Published: ${r.published?'Yes':'No'}</p></div><div class="record-actions"><button class="btn light" data-edit="${r.id}">Edit</button><button class="btn danger" data-del="${r.id}">Delete</button></div></div>`).join(''):'<p class="small">No records yet.</p>';box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRecord(key,def,b.dataset.edit));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteRecord(key,def,b.dataset.del));}
async function editRecord(key,def,id){const {data,error}=await sb.from(def.table).select('*').eq('id',id).single();if(error){setStatus(error.message,'error');return}editing=id;def.fields.forEach(([k,,type])=>{const e=$('#f_'+k);if(!e)return;if(type==='checkbox')e.checked=!!data[k];else if(type==='file'||type==='image'){const h=$('#u_'+k);if(h)h.value=data[k]||'';const wrap=e.parentElement;const old=wrap.querySelector('.current-file');if(old)old.remove();if(data[k]){const n=document.createElement('div');n.className='current-file';n.innerHTML=`Current: <a href="${esc(data[k])}" target="_blank" rel="noopener">Open current file</a>`;e.after(n)}}else if(type!=='labselect')e.value=data[k]??''});if(def.fields.some(f=>f[2]==='labselect'))await fillLabSelect(data.laboratory_id||'');window.scrollTo({top:0,behavior:'smooth'});setStatus('Editing record '+id)}
function safeName(name){return name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')||'file'}
async function uploadSelected(file,key){const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`${key}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from(ASSET_BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,...(file.type?{contentType:file.type}:{})});if(error)throw error;const {data}=sb.storage.from(ASSET_BUCKET).getPublicUrl(path);return data.publicUrl}
async function save(e,key,def){e.preventDefault();const btn=$('#saveBtn');btn.disabled=true;btn.textContent='Saving…';try{const payload={};for(const [k,,type] of def.fields){const el=$('#f_'+k);if(type==='checkbox')payload[k]=el.checked;else if(type==='file'||type==='image')payload[k]=$('#u_'+k)?.value||null;else payload[k]=el.value||null}
 for(const [k,,type] of def.fields){if(type==='file'||type==='image'){const file=$('#f_'+k)?.files?.[0];if(file){setStatus(`Uploading ${file.name}…`);payload[k]=await uploadSelected(file,key);}}}
 const q=editing?sb.from(def.table).update(payload).eq('id',editing):sb.from(def.table).insert(payload);const {error}=await q;if(error)throw error;setStatus(editing?'Record updated.':'Record created.','ok');editing=null;document.querySelector('#recordForm')?.reset();document.querySelectorAll('input[type=file]').forEach(x=>x.value='');document.querySelectorAll('input[type=hidden]').forEach(x=>x.value='');await refreshRecords(key,def);if(def.fields.some(f=>f[2]==='labselect'))await fillLabSelect();}catch(error){setStatus(error.message||String(error),'error')}finally{btn.disabled=false;btn.textContent='Save'}}
async function deleteRecord(key,def,id){if(!confirm('Delete this record?'))return;const {error}=await sb.from(def.table).delete().eq('id',id);if(error){setStatus(error.message,'error');return}setStatus('Record deleted.','ok');refreshRecords(key,def)}
async function galleryPhotos(){const {data:gals,error}=await sb.from('galleries').select('id,title').order('created_at',{ascending:false});if(error){setStatus(error.message,'error');return}const opts=(gals||[]).map(g=>`<option value="${esc(g.id)}">${esc(g.title)}</option>`).join('');$('#content').innerHTML=`<div id="pageStatus" class="status hidden"></div><div class="panel"><h2>Gallery Photos</h2><p class="small">Choose a gallery and upload one or more photos. Photos appear inside the published gallery.</p><form id="galleryPhotoForm"><div class="form-grid"><div class="field"><label>Gallery</label><select id="gp_gallery" required><option value="">Select gallery</option>${opts}</select></div><div class="field"><label>Caption (optional)</label><input id="gp_caption" type="text"></div><div class="field full"><label>Photos</label><input id="gp_files" type="file" accept="image/*" multiple required><span class="small">You can select multiple images at once.</span></div></div><div class="actions"><button class="btn gold" id="gp_save" type="submit">Upload Photos</button></div></form></div><div class="panel"><h2>Existing gallery photos</h2><div id="galleryPhotoRecords" class="records">Loading…</div></div>`;$('#galleryPhotoForm').onsubmit=uploadGalleryPhotos;await refreshGalleryPhotos()}
async function refreshGalleryPhotos(){const {data,error}=await sb.from('gallery_photos').select('id,image_url,caption,gallery_id,galleries(title)').order('created_at',{ascending:false});const box=$('#galleryPhotoRecords');if(!box)return;if(error){box.innerHTML=`<p class="status error">${esc(error.message)}</p>`;return}box.innerHTML=(data||[]).length?(data||[]).map(r=>`<div class="record"><div class="photo-record"><img src="${esc(r.image_url)}" alt="${esc(r.caption||'Gallery photo')}"><div><h3>${esc(r.galleries?.title||'Gallery')}</h3><p>${esc(r.caption||'No caption')}</p></div></div><div class="record-actions"><button class="btn danger" data-gp-del="${r.id}">Delete</button></div></div>`).join(''):'<p class="small">No gallery photos yet.</p>';box.querySelectorAll('[data-gp-del]').forEach(b=>b.onclick=()=>deleteGalleryPhoto(b.dataset.gpDel))}
async function uploadGalleryPhotos(e){e.preventDefault();const btn=$('#gp_save');const files=[...($('#gp_files').files||[])];if(!files.length)return;btn.disabled=true;btn.textContent='Uploading…';try{const galleryId=$('#gp_gallery').value,caption=$('#gp_caption').value||null;for(let i=0;i<files.length;i++){setStatus(`Uploading photo ${i+1} of ${files.length}…`);const url=await uploadSelected(files[i],'gallery');const {error}=await sb.from('gallery_photos').insert({gallery_id:galleryId,image_url:url,caption});if(error)throw error}setStatus(`${files.length} photo(s) uploaded.`,'ok');$('#galleryPhotoForm').reset();await refreshGalleryPhotos()}catch(error){setStatus(error.message||String(error),'error')}finally{btn.disabled=false;btn.textContent='Upload Photos'}}
async function deleteGalleryPhoto(id){if(!confirm('Delete this gallery photo?'))return;const {error}=await sb.from('gallery_photos').delete().eq('id',id);if(error){setStatus(error.message,'error');return}setStatus('Gallery photo deleted.','ok');refreshGalleryPhotos()}
async function render(){menu();if(current==='dashboard')return dashboard();if(current==='gallery_photos')return galleryPhotos();return page(current)}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(session){$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');render()}else $('#loginView').classList.remove('hidden');}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(error){$('#loginStatus').textContent=error.message;$('#loginStatus').className='status error'}else boot()};$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};sb.auth.onAuthStateChange(()=>{});boot();
})();
